"""tables_ordered_correctly

Revision ID: 00cd7fdc75d9
Revises: 3fbb8e1ea73d
Create Date: 2026-06-11 20:03:26.863926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cd7fdc75d9'
down_revision = '3fbb8e1ea73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapped_exams', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'exams', ['sending_exam_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'exams', ['host_exam_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    # ### end Alembic commands ###

    # ---- database triggers (moved out of models.py) ----

    # on INSERT of a document, the associated application must be notified,
    # changed status and check if business rules apply correctly
    op.execute("""
CREATE OR REPLACE FUNCTION update_application_on_upload() RETURNS TRIGGER AS $$
DECLARE
    app_status VARCHAR(32);
BEGIN
    SELECT status
        INTO app_status
        FROM applications
        WHERE id = NEW.application_id;

    IF NEW.document_type = 'learning_agreement' THEN
        -- check if the status of associated application is valid
        IF app_status NOT IN ('created','learning_agreement_pending') THEN
            RAISE EXCEPTION 'new learning agreement document cannot be changed while the application is in % status', app_status;
        END IF;

        IF app_status = 'created' THEN
            UPDATE applications SET status='learning_agreement_pending' WHERE id=NEW.application_id;
        END IF;
    ELSE
        -- if it's not a LA, it must be a transcript of records (because of check constraint), check if the status of associated application is valid
        IF app_status <> 'exam_recognition' THEN
            RAISE EXCEPTION 'new transcript of records document cannot be changed while the application is in % status', app_status;
        END IF;
    END IF;

    RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER applicaiton_update_on_upload
BEFORE INSERT ON uploaded_documents
FOR EACH ROW
    EXECUTE FUNCTION update_application_on_upload();
""")

    # on INSERT/UPDATE of a mapped_exams row, verifies that
    #   1) host_exam_id    belongs to the application's host_institution
    #   2) sending_exam_id belongs to the application's sending_institution
    op.execute("""
CREATE OR REPLACE FUNCTION check_mapped_exam_institutions() RETURNS TRIGGER AS $$
DECLARE
    app_host_inst       INT;
    app_sending_inst    INT;
    host_exam_inst      INT;
    sending_exam_inst   INT;
BEGIN
    SELECT host_institution, sending_institution
        INTO app_host_inst, app_sending_inst
        FROM applications
        WHERE id = NEW.application_id;

    SELECT id_institution INTO host_exam_inst
        FROM exams WHERE id = NEW.host_exam_id;

    SELECT id_institution INTO sending_exam_inst
        FROM exams WHERE id = NEW.sending_exam_id;

    IF host_exam_inst <> app_host_inst THEN
        RAISE EXCEPTION 'host_exam_id institution does not match application host_institution';
    END IF;

    IF sending_exam_inst <> app_sending_inst THEN
        RAISE EXCEPTION 'sending_exam_id institution does not match application sending_institution';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER mapped_exam_institutions_check
BEFORE INSERT OR UPDATE ON mapped_exams
FOR EACH ROW
    EXECUTE FUNCTION check_mapped_exam_institutions();
""")

    # on INSERT/UPDATE of an application, verifies that the referent (if not null)
    # has role='referent' and the student has role='student'
    op.execute("""
CREATE OR REPLACE FUNCTION check_application_data() RETURNS TRIGGER AS $$
BEGIN
    -- valid referent, institution is checked by existing constraint
    IF NEW.referent_id IS NOT NULL AND NOT EXISTS(
        SELECT 1
        FROM users
        WHERE id = NEW.referent_id
        AND role='referent'
    ) THEN
        RAISE EXCEPTION 'application referent must have role=referent';
    END IF;

    -- valid student, institution is checked by existing constraint
    IF NOT EXISTS(
        SELECT 1
        FROM users
        WHERE id=NEW.user_id
        AND role='student'
    ) THEN
        RAISE EXCEPTION 'application student must have role=student';
    END IF;

    -- check that a application cannot be created already past the initial statuses
    IF TG_OP='INSERT' AND NEW.status NOT IN('created','learning_agreement_pending') THEN
        RAISE EXCEPTION 'application status cannot start with %', NEW.status;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER application_data_check
BEFORE INSERT OR UPDATE ON applications
FOR EACH ROW
    EXECUTE FUNCTION check_application_data();
""")

    # enforces the allowed status transitions of an application
    op.execute("""
CREATE OR REPLACE FUNCTION check_application_status_workflow() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status='created' AND OLD.status NOT IN ('learning_agreement_pending', 'created') THEN
        RAISE EXCEPTION 'cannot move to created without an approved learning agreement';
    END IF;

    -- created -> pre_departure_completed
    IF NEW.status='pre_departure_completed' AND OLD.status='created' THEN
        -- check if associated learning agreement exists and has been approved
        IF NOT EXISTS ( SELECT 1
                FROM uploaded_documents
                WHERE application_id=NEW.id
                AND document_type='learning_agreement'
                AND status='approved'
            ) THEN
            RAISE EXCEPTION 'cannot move to pre_departure_completed without an approved learning agreement';
        END IF;

        -- check if mapped exams exists and are all approved (search for at least 1 that has not been approved)
        IF EXISTS (SELECT 1
            FROM mapped_exams
            WHERE application_id=NEW.id
            AND status<>'approved'
            ) THEN
            RAISE EXCEPTION 'cannot move to pre_departure_completed: all mapped exams must be approved';
        END IF;
    ELSEIF NEW.status='pre_departure_completed' AND OLD.status<>'created' THEN
        RAISE EXCEPTION 'application status cannot pass from % -> %', OLD.status, NEW.status;
    END IF;

    -- pre_departure_completed -> mobility_ongoing
    IF NEW.status='mobility_ongoing' AND OLD.status<>'pre_departure_completed' THEN
        RAISE EXCEPTION 'application status cannot pass from % -> %', OLD.status, NEW.status;
    END IF;

    -- mobility_ongoing -> exam_recognition
    IF NEW.status='exam_recognition' AND OLD.status='mobility_ongoing' THEN
        -- update the mapped exams to 'pending' because a grade is expected
        UPDATE mapped_exams
        SET status='pending'
        WHERE application_id=NEW.id;
    ELSEIF NEW.status='exam_recognition' AND OLD.status<>'mobility_ongoing' THEN
        RAISE EXCEPTION 'application status cannot pass from % -> %', OLD.status, NEW.status;
    END IF;

    IF NEW.status='closed' AND OLD.status='exam_recognition' THEN
        -- check uploaded transcript of records, if it exists and has been approved
        IF NOT EXISTS (SELECT 1
            FROM uploaded_documents
            WHERE application_id=NEW.id
            AND document_type='transcript'
            AND status='approved'
            ) THEN
            RAISE EXCEPTION 'approved transcript of records required';
        END IF;

        -- check if all mapped_exams are graded and approved (if at least 1 is not)
        IF EXISTS(SELECT 1
                FROM mapped_exams
                WHERE application_id=NEW.id AND
                (grade IS NULL OR grade=-1 OR status <> 'approved')
            ) THEN
            RAISE EXCEPTION 'all exams must be approved and require a grade';
        END IF;
    ELSEIF NEW.status='closed' AND OLD.status<>'exam_recognition' THEN
        RAISE EXCEPTION 'application status cannot pass from % -> %', OLD.status, NEW.status;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER applicaiton_status_workflow
BEFORE UPDATE ON applications
FOR EACH ROW
    WHEN (NEW.status<>OLD.status)
    EXECUTE FUNCTION check_application_status_workflow();
""")

    # when the status of a mapped_exam changes to 'approved' or 'rejected',
    # automatically stamps decision_date with the current timestamp
    op.execute("""
CREATE OR REPLACE FUNCTION check_update_status_mapped_exams() RETURNS TRIGGER AS $$
DECLARE
    app_status VARCHAR(32);
BEGIN
    IF NEW.status IN ('approved', 'rejected') THEN
        -- prevent status change when application is not in adequate status
        SELECT status INTO app_status
        FROM applications
        WHERE id = NEW.application_id;
        IF app_status NOT IN ('created','learning_agreement_pending','mobility_ongoing','exam_recognition') THEN
            RAISE EXCEPTION 'cannot change exam status when associated application is in % status', app_status;
        END IF;

        NEW.decision_date := CURRENT_TIMESTAMP;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER mapped_exam_update_status_check
BEFORE UPDATE ON mapped_exams
FOR EACH ROW
WHEN (OLD.status <> NEW.status)
    EXECUTE FUNCTION check_update_status_mapped_exams();
""")

    # when the status of an uploaded_document changes to 'approved' or 'rejected',
    # automatically stamps decision_date with the current timestamp
    op.execute("""
CREATE OR REPLACE FUNCTION check_document_status_update() RETURNS TRIGGER AS $$
DECLARE
    app_status VARCHAR(32);
BEGIN
    SELECT status INTO app_status
    FROM applications
    WHERE id = NEW.application_id;

    IF NEW.status IN ('approved', 'rejected') THEN
        -- prevent status change when application is not in adequate status
        IF NEW.document_type='learning_agreement' THEN
            IF app_status NOT IN ('created','learning_agreement_pending') THEN
                RAISE EXCEPTION 'cannot change document when associated application is in % status', app_status;
            END IF;
        END IF;
        IF NEW.document_type='transcript' THEN
            IF app_status <> 'exam_recognition' THEN
                RAISE EXCEPTION 'cannot change document status when associated application is in % status', app_status;
            END IF;
        END IF;

        NEW.decision_date := CURRENT_TIMESTAMP;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER document_status_update_check
BEFORE UPDATE ON uploaded_documents
FOR EACH ROW
WHEN (OLD.status <> NEW.status)
    EXECUTE FUNCTION check_document_status_update();
""")

    # after an INSERT on partner_institution, automatically inserts the reciprocal
    # row (B -> A) if it does not already exist, so partnership stays symmetrical
    op.execute("""
CREATE OR REPLACE FUNCTION mirror_partner_institution() RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM partner_institution
        WHERE id_institution = NEW.id_partner_institution
          AND id_partner_institution = NEW.id_institution
    ) THEN
        INSERT INTO partner_institution (id_institution, id_partner_institution)
            VALUES (NEW.id_partner_institution, NEW.id_institution);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER partner_institution_symmetry
AFTER INSERT ON partner_institution
FOR EACH ROW
    EXECUTE FUNCTION mirror_partner_institution();
""")

    # when the status of a la_modification changes to 'approved' or 'rejected',
    # automatically stamps decision_date with the current timestamp
    op.execute("""
CREATE OR REPLACE FUNCTION set_modification_decision_date() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status IN ('approved', 'rejected') THEN
        NEW.decision_date := CURRENT_TIMESTAMP;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER la_modification_decision_date
BEFORE UPDATE ON la_modifications
FOR EACH ROW
WHEN (OLD.status <> NEW.status)
    EXECUTE FUNCTION set_modification_decision_date();
""")


def downgrade():
    # ---- drop the database triggers and their functions ----
    op.execute("DROP TRIGGER IF EXISTS la_modification_decision_date ON la_modifications;")
    op.execute("DROP FUNCTION IF EXISTS set_modification_decision_date();")

    op.execute("DROP TRIGGER IF EXISTS partner_institution_symmetry ON partner_institution;")
    op.execute("DROP FUNCTION IF EXISTS mirror_partner_institution();")

    op.execute("DROP TRIGGER IF EXISTS document_status_update_check ON uploaded_documents;")
    op.execute("DROP FUNCTION IF EXISTS check_document_status_update();")

    op.execute("DROP TRIGGER IF EXISTS mapped_exam_update_status_check ON mapped_exams;")
    op.execute("DROP FUNCTION IF EXISTS check_update_status_mapped_exams();")

    op.execute("DROP TRIGGER IF EXISTS applicaiton_status_workflow ON applications;")
    op.execute("DROP FUNCTION IF EXISTS check_application_status_workflow();")

    op.execute("DROP TRIGGER IF EXISTS application_data_check ON applications;")
    op.execute("DROP FUNCTION IF EXISTS check_application_data();")

    op.execute("DROP TRIGGER IF EXISTS mapped_exam_institutions_check ON mapped_exams;")
    op.execute("DROP FUNCTION IF EXISTS check_mapped_exam_institutions();")

    op.execute("DROP TRIGGER IF EXISTS applicaiton_update_on_upload ON uploaded_documents;")
    op.execute("DROP FUNCTION IF EXISTS update_application_on_upload();")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapped_exams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
