"""tables_ordered_correctly

Revision ID: 00cd7fdc75d9
Revises: 3fbb8e1ea73d
Create Date: 2026-06-11 20:03:26.863926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cd7fdc75d9'
down_revision = '3fbb8e1ea73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapped_exams', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'exams', ['sending_exam_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'exams', ['host_exam_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapped_exams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
