"""empty message

Revision ID: 0cc8de7364e3
Revises: a1f4c2e9b7d0
Create Date: 2026-07-02 15:24:55.293220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc8de7364e3'
down_revision = 'a1f4c2e9b7d0'
branch_labels = None
depends_on = None


def upgrade():
    # NOTE: original autogenerate emitted plain drop_index calls, but most of
    # these indexes are never created by any migration or by database/overseas.sql
    # (fresh installs have none of them). A bare DROP INDEX therefore failed with
    # UndefinedObject and rolled back the whole boot-time `flask db upgrade`.
    # Use idempotent DROP INDEX IF EXISTS so this runs on both fresh and legacy DBs.
    dropped_indexes = [
        'idx_applications_date_submitted_desc',
        'idx_applications_host_institution',
        'idx_applications_referent_id',
        'idx_applications_sending_institution',
        'idx_applications_status',
        'idx_applications_user_id',
        'idx_exams_id_institution',
        'idx_la_modification_exams_modification_id',
        'idx_la_modifications_app_status',
        'idx_mapped_exams_application_id',
        'idx_mapped_exams_application_status',
        'idx_mapped_exams_host_exam_id',
        'idx_mapped_exams_sending_exam_id',
        'idx_partner_institution_partner_id',
        'idx_uploaded_documents_app_type_date',
        'idx_uploaded_documents_app_type_status',
        'idx_uploaded_documents_application_id',
        'idx_uploaded_documents_user_id',
        'idx_users_id_institution',
        'idx_users_institution_role',
    ]
    for name in dropped_indexes:
        op.execute('DROP INDEX IF EXISTS "%s"' % name)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_institution_role'), ['id_institution', 'role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_id_institution'), ['id_institution'], unique=False)

    with op.batch_alter_table('uploaded_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_uploaded_documents_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_uploaded_documents_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_uploaded_documents_app_type_status'), ['application_id', 'document_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_uploaded_documents_app_type_date'), ['application_id', 'document_type', sa.literal_column('date_updated DESC')], unique=False)

    with op.batch_alter_table('partner_institution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_partner_institution_partner_id'), ['id_partner_institution'], unique=False)

    with op.batch_alter_table('mapped_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_mapped_exams_sending_exam_id'), ['sending_exam_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_mapped_exams_host_exam_id'), ['host_exam_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_mapped_exams_application_status'), ['application_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_mapped_exams_application_id'), ['application_id'], unique=False)

    with op.batch_alter_table('la_modifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_la_modifications_app_status'), ['application_id', 'status'], unique=False)

    with op.batch_alter_table('la_modification_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_la_modification_exams_modification_id'), ['modification_id'], unique=False)

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_exams_id_institution'), ['id_institution'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_sending_institution'), ['sending_institution'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_referent_id'), ['referent_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_host_institution'), ['host_institution'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_date_submitted_desc'), [sa.literal_column('date_submitted DESC')], unique=False)

    # ### end Alembic commands ###
