"""initial schema

Revision ID: 33e4600ce890
Revises: 
Create Date: 2026-07-04 22:03:54.152799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e4600ce890'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('id_institution', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_institution'], ['institutions.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'id_institution')
    )
    op.create_table('partner_institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_institution', sa.Integer(), nullable=False),
    sa.Column('id_partner_institution', sa.Integer(), nullable=False),
    sa.CheckConstraint('id_institution <> id_partner_institution', name='self_partner'),
    sa.ForeignKeyConstraint(['id_institution'], ['institutions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_partner_institution'], ['institutions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_institution', 'id_partner_institution')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('id_institution', sa.Integer(), nullable=False),
    sa.CheckConstraint("role = 'student' OR role = 'referent' OR role = 'staff'", name='allowed_user_roles'),
    sa.ForeignKeyConstraint(['id_institution'], ['institutions.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id', 'id_institution')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('date_submitted', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_arrived', sa.Date(), nullable=True),
    sa.Column('date_departure', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('referent_id', sa.Integer(), nullable=True),
    sa.Column('sending_institution', sa.Integer(), nullable=False),
    sa.Column('host_institution', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("semester IN ('first', 'second', 'full')", name='valid_semester'),
    sa.CheckConstraint("status IN ('created', 'learning_agreement_pending', 'pre_departure_completed', 'mobility_ongoing', 'exam_recognition', 'closed')", name='valid_status'),
    sa.CheckConstraint('(date_arrived IS NULL OR EXTRACT(YEAR FROM date_arrived) IN (year, year + 1)) AND (date_departure IS NULL OR EXTRACT(YEAR FROM date_departure) IN (year, year + 1))', name='valid_academic_year'),
    sa.CheckConstraint('date_arrived IS NULL OR date_departure IS NULL OR date_departure >= date_arrived', name='valid_mobility_dates'),
    sa.CheckConstraint('host_institution <> sending_institution', name='different_host_sending'),
    sa.ForeignKeyConstraint(['host_institution'], ['institutions.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['referent_id', 'sending_institution'], ['users.id', 'users.id_institution'], ),
    sa.ForeignKeyConstraint(['referent_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sending_institution', 'host_institution'], ['partner_institution.id_institution', 'partner_institution.id_partner_institution'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['sending_institution'], ['institutions.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'sending_institution'], ['users.id', 'users.id_institution'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapped_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('date_passed', sa.Date(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('host_exam_id', sa.Integer(), nullable=False),
    sa.Column('sending_exam_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='valid_status'),
    sa.CheckConstraint('(grade = -1 AND date_passed IS NULL) OR (grade <> -1 AND date_passed IS NOT NULL)', name='valid_grade_date'),
    sa.CheckConstraint('grade = -1 OR (grade > 17 AND grade <= 30)', name='valid_grade'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_exam_id'], ['exams.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sending_exam_id'], ['exams.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'host_exam_id'),
    sa.UniqueConstraint('application_id', 'sending_exam_id')
    )
    op.create_table('uploaded_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("document_type IN ('learning_agreement', 'transcript')", name='valid_type'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='valid_status'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('la_modifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='valid_modification_status'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['uploaded_documents.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('la_modification_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modification_id', sa.Integer(), nullable=False),
    sa.Column('host_exam_id', sa.Integer(), nullable=False),
    sa.Column('sending_exam_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('date_passed', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decision_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_exam_id'], ['exams.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modification_id'], ['la_modifications.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sending_exam_id'], ['exams.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modification_id', 'host_exam_id'),
    sa.UniqueConstraint('modification_id', 'sending_exam_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('la_modification_exams')
    op.drop_table('la_modifications')
    op.drop_table('uploaded_documents')
    op.drop_table('mapped_exams')
    op.drop_table('applications')
    op.drop_table('users')
    op.drop_table('partner_institution')
    op.drop_table('exams')
    op.drop_table('institutions')
    # ### end Alembic commands ###
