"""initial migration

Revision ID: 3c053448610d
Revises: 
Create Date: 2026-06-08 14:43:21.703513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c053448610d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
