"""tables_completed1

Revision ID: 3fbb8e1ea73d
Revises: 10e3c9883cdc
Create Date: 2026-06-11 19:48:02.637680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fbb8e1ea73d'
down_revision = '10e3c9883cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id', 'id_institution'])
        batch_op.drop_constraint(batch_op.f('users_id_institution_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'institutions', ['id_institution'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_arrived', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_departure', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('referent_id', sa.Integer(), nullable=True))
        batch_op.alter_column('semester',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('date_submitted',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('applications_sending_institution_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('applications_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('applications_host_institution_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id', 'sending_institution'], ['id', 'id_institution'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'institutions', ['sending_institution'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'institutions', ['host_institution'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'users', ['referent_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['code', 'id_institution'])
        batch_op.drop_constraint(batch_op.f('exams_id_institution_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'institutions', ['id_institution'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('mapped_exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_passed', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('decision_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('previous_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('host_exam_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sending_exam_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['application_id', 'host_exam_id', 'sending_exam_id'])
        batch_op.drop_constraint(batch_op.f('mapped_exams_exam_code_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('mapped_exams_application_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('mapped_exams_mapped_exam_code_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_column('exam_code')
        batch_op.drop_column('mapped_exam_code')

    with op.batch_alter_table('partner_institution', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_institution', 'id_partner_institution'])
        batch_op.drop_constraint(batch_op.f('partner_institution_id_partner_institution_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('partner_institution_id_institution_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'institutions', ['id_institution'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'institutions', ['id_partner_institution'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('uploaded_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('decision_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uploaded_documents_application_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uploaded_documents_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exams', ['sending_exam_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'exams', ['host_exam_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_id_institution_fkey'), 'institutions', ['id_institution'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('uploaded_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('uploaded_documents_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('uploaded_documents_application_id_fkey'), 'applications', ['application_id'], ['id'])
        batch_op.drop_column('notes')
        batch_op.drop_column('decision_date')
        batch_op.drop_column('status')
        batch_op.drop_column('date_updated')

    with op.batch_alter_table('partner_institution', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('partner_institution_id_institution_fkey'), 'institutions', ['id_institution'], ['id'])
        batch_op.create_foreign_key(batch_op.f('partner_institution_id_partner_institution_fkey'), 'institutions', ['id_partner_institution'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('mapped_exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mapped_exam_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('exam_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mapped_exams_mapped_exam_code_fkey'), 'exams', ['mapped_exam_code'], ['code'])
        batch_op.create_foreign_key(batch_op.f('mapped_exams_application_id_fkey'), 'applications', ['application_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('mapped_exams_exam_code_fkey'), 'exams', ['exam_code'], ['code'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sending_exam_id')
        batch_op.drop_column('host_exam_id')
        batch_op.drop_column('previous_id')
        batch_op.drop_column('notes')
        batch_op.drop_column('decision_date')
        batch_op.drop_column('status')
        batch_op.drop_column('grade')
        batch_op.drop_column('date_passed')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exams_id_institution_fkey'), 'institutions', ['id_institution'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('applications_host_institution_fkey'), 'institutions', ['host_institution'], ['id'])
        batch_op.create_foreign_key(batch_op.f('applications_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('applications_sending_institution_fkey'), 'institutions', ['sending_institution'], ['id'])
        batch_op.alter_column('date_submitted',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('semester',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('referent_id')
        batch_op.drop_column('notes')
        batch_op.drop_column('date_departure')
        batch_op.drop_column('date_arrived')

    # ### end Alembic commands ###
