"""empty message

Revision ID: b9d9d1de9be5
Revises: 7a1826463fd0
Create Date: 2026-07-03 17:52:26.870728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d9d1de9be5'
down_revision = '7a1826463fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapped_exams', schema=None) as batch_op:
        batch_op.drop_column('previous_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapped_exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
